os: linux
dist: trusty

services: docker

language: bash

branches:
  only:
    - master
    - develop

before_script:
  - env | sort
  - name="monogramm/docker-penpot-builder"
  - image="monogramm/docker-penpot-builder:travis"
  - dir="."

script:
  - travis_retry docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --name "$name" -d "$image"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env: # Environments
